<template>
  <v-row class="mb-1">
    <v-col
      cols="12"
      md="4"
    >
      <v-btn
        size="x-large"
        width="100%"
        elevation="0"
        color="amber-darken-2"
        prepend-icon="mdi-cart-outline"
        text="Shop"
      />
    </v-col>
    <v-col
      cols="12"
      md="4"
    >
      <v-btn
        size="x-large"
        width="100%"
        elevation="0"
        color="teal"
        prepend-icon="mdi-egg"
        text="Nursery"
      />
    </v-col>
    <v-col
      cols="12"
      md="4"
    >
      <v-btn
        size="x-large"
        width="100%"
        elevation="0"
        color="red-darken-3"
        prepend-icon="mdi-sword"
        text="Fight"
      />
    </v-col>
    <v-col
      cols="12"
      md="4"
    >
      <v-btn
        size="x-large"
        width="100%"
        elevation="0"
        color="purple-darken-1"
        prepend-icon="mdi-emoticon-devil"
        text="Monsters"
      />
    </v-col>
    <v-col
      cols="12"
      md="4"
    >
      <v-btn
        size="x-large"
        width="100%"
        elevation="0"
        color="green-darken-2"
        prepend-icon="mdi-briefcase"
        text="Items"
      />
    </v-col>
    <v-col
      cols="12"
      md="4"
    >
      <v-btn
        size="x-large"
        width="100%"
        elevation="0"
        color="blue-darken-2"
        prepend-icon="mdi-hanger"
        text="Equipment"
      />
    </v-col>
  </v-row>
</template>